# Site wide configuration

title: Kerkesix
description: Kerkesix ry on monipuolista urheilua ja ulkoilua harrastavien ihmisten seura, joka pyrkii kehittämään jäsentensä fyysistä ja henkistä hyvinvointia tarjoamalla mahdollisuuksia toteuttaa itseään mukavassa seurassa.
# 120x120 px default image used for Twitter summary card
logo: twitter-logo.png
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:
timezone: Europe/Helsinki
encoding: utf-8
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

# Site owner
owner:
  name: Kerkesix ry
  email: info@kerkesix.fi
  twitter: kerkesix
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: kerkesix

# Analytics and webmaster tools stuff goes here
google_analytics: UA-24940535-1
google_verify:

exclude:
  - "*.less"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - .github
  - .gitignore
  - .gitattributes
  - .jshintrc
  - .firebaserc
  - .editorconfig
  - CHANGELOG
  - Capfile
  - cloudbuild.yaml
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Makefile
  - Rakefile
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
