# Site wide configuration

title: Kerkesix
description: Kerkesix ry on monipuolista urheilua ja ulkoilua harrastavien ihmisten seura, joka pyrkii kehittämään jäsentensä fyysistä ja henkistä hyvinvointia tarjoamalla mahdollisuuksia toteuttaa itseään mukavassa seurassa.
# 120x120 px default image used for Twitter summary card
logo: twitter-logo.png
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://kerkesix.fi
feed_url: http://feeds.feedburner.com/kerkesix
timezone:    Europe/Helsinki
encoding:    UTF-8

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Site owner
owner:
  name: Kerkesix ry
  email: info@kerkesix.fi
  twitter: kerkesix
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: kerkesix

# Analytics and webmaster tools stuff goes here
google_analytics: UA-24940535-1
google_verify:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
