# Builds the Next.js site and deploys it to Firebase hosting
name: Deploy each push
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Build site
      #   uses: docker://jekyll/builder:4.1.0
      #   with:
      #     args: jekyll build

      - name: Archive built site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: site
          path: out

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
